---
title: "Rockland Data"
author: "John Flournoy"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lme4)
```

```{r}
mri_data_dir <- '/data/jflournoy/rockland/'
derivs_dir <- paste0(mri_data_dir, '/derivatives/')
session_file_dir <- '/data/jflournoy/rockland/derivatives/new_session_tsvs/session_tsv_files/'
subj_pattern <- 'sub-A[[:digit:]]{8}'

raw_dirs <- data_frame(sub = dir(mri_data_dir)) %>%
  filter(grepl(pattern = subj_pattern, x = sub)) %>%
  group_by(sub) %>%
  do({
    inraw <- data_frame(session = dir(paste0(mri_data_dir, '/', .$sub))) %>%
      filter(grepl('ses-', session)) 
    inraw
  }) %>%
  extract(col = session, 
          into = c('sestype', 'sesnum', 'sesrepeat'), 
          regex = 'ses-([[:alpha:]]+)([[:digit:]A])(R)*',
          remove = F) %>%
  mutate(sesnum_conv = as.character(ifelse(sesnum == 'A', 2, sesnum)),
         ses_repeat =  ifelse(sesrepeat %in% 'R', .5, 0),
         ses_order_raw = as.numeric(sesnum_conv) + ses_repeat) %>%
  arrange(sub, ses_order_raw) %>%
  group_by(sub) %>%
  mutate(ses_order = 1:n())

raw_data_dir_sum <- raw_dirs %>%
  group_by(sub) %>%
  summarize(n_obs_raw = n(),
            long_raw = n_obs_raw > 1)

processed_dirs <- data_frame(sub = dir(derivs_dir))%>%
  filter(grepl(pattern = subj_pattern, x = sub)) %>%
  extract(sub, into = c('sub', 'session','long_tag'),
          regex = '(sub-A[[:digit:]]{8})_*(ses-[[:alnum:]]+)*\\.*(long)*.*') %>%
  group_by(sub) %>%
  mutate(long = 'long' %in% long_tag) %>%
  distinct(sub, session, .keep_all = T) 

processed_dirs_sum <-processed_dirs %>%
  summarize(n_obs_ppc = n(),
            long_ppc = all(long))

combined_sum <- full_join(raw_data_dir_sum, processed_dirs_sum) %>%
  mutate(error = (long_ppc != long_raw) | is.na(long_ppc))

combined_sum %>%
  group_by(error) %>%
  summarize(n = n()) %>%
  knitr::kable()

completed_subs <- combined_sum %>% 
  filter(!error) %>%
  select(sub)

completed_sessions <- processed_dirs %>%
  mutate(n_obs_ppc = n(),
         long_ppc = all(long)) %>%
  left_join(combined_sum)

completed <- left_join(completed_subs, completed_sessions) %>%
  mutate(session_old = session,
         session = ifelse(n_obs_raw == 1, 'singular', session_old))
```

```{r}
session_file_names_raw <- data_frame(session_file = dir(path = session_file_dir)) %>%
  filter(grepl(pattern = subj_pattern, x = session_file)) %>%
  extract(session_file, into = c('sub'), regex = paste0('(', subj_pattern, ').*'), remove = F)

session_data <- data_frame(sub = dir(path = mri_data_dir)) %>%
  filter(grepl(pattern = subj_pattern, x = sub)) %>% 
  left_join(session_file_names_raw) %>%
  group_by(sub, session_file) %>%
  do({
    # print(paste0('Reading ', .$session_file[[1]]))
    aDF <- read_csv(paste0(session_file_dir, .$session_file))
    # print(dim(aDF))
    # print(names(aDF))
    aDF[,2:4]
    }) %>%
  arrange(sub, age) %>%
  group_by(sub) %>%
  mutate(ses_order = 1:n(),
         max_ses = max(ses_order)) %>%
  mutate(session_id_old = session_id,
         session_id = ifelse(max_ses == 1, 'singular', session_id_old))
```

```{r}
completed_with_age <- left_join(completed, session_data, by = c('sub'='sub', 'session'='session_id')) %>%
  arrange(sub, age) %>%
  select(sub, session, session_old, session_id_old, age, everything())

completed_with_age_cleaned <- completed_with_age %>%
  filter(!is.na(age)) %>%
  mutate(session_singular = session,
         session = ifelse(session == 'singular', session_id_old, session_singular)) %>%
  distinct(sub, session, age, .keep_all = T) %>%
  group_by(sub) %>%
  mutate(n_obs_final = n()) %>%
  select(sub, session, age, long, n_obs_raw, n_obs_ppc, n_obs_final, session_singular)

completed_cln_aga_loc <- completed_with_age_cleaned %>%
  mutate(data_path = ifelse(long, 
                            file.path(derivs_dir, paste0(sub, '_', session, '.long.', sub)), 
                            file.path(derivs_dir, paste0(sub))),
         data_path_exists = dir.exists(data_path)) %>%
  filter(data_path_exists)
```


```{r}
rockland_aparc2009 <- completed_cln_aga_loc %>%
  arrange(sub, age) %>%
  group_by(sub, session, age, n_obs_final) %>%
  do({
    col_names <- c('StructName', 'NumVert', 'SurfArea', 'GrayVol', 'ThickAvg', 'ThickStd', 'MeanCurv', 'GausCurv', 'FoldInd', 'CurvInd')
    tryCatch({
      aDF.lh <- read_table(file.path(.$data_path[[1]], 'stats', 'lh.aparc.a2009s.stats'),
                         skip = 60, 
                         col_names = col_names)
    }, error = function(e){
      aDF.lh <<- data_frame(error = list(e))
      return(aDF.lh)
    })
    tryCatch({
      aDF.rh <- read_table(file.path(.$data_path[[1]], 'stats', 'rh.aparc.stats'),
                         skip = 60, 
                         col_names = col_names)
    }, error = function(e){
      aDF.rh <<- data_frame(error = list(e))
      return(aDF.rh)
    })
    aDF.lh$h <- 'l'
    aDF.rh$h <- 'r'
    aDF <- bind_rows(aDF.lh, aDF.rh)
    return(aDF)
  })
```

```{r}
rockland_aparc2009_clean1 <- rockland_aparc2009 %>%
  filter(is.null(error[[1]])) %>%
  arrange(sub, age, StructName) %>%
  ungroup() %>%
  mutate(age = as.numeric(age),
         age_c = age - mean(age),
         age_c_2 = age_c^2,
         ThickAvg = as.numeric(ThickAvg))

age_diffs <- rockland_aparc2009_clean1 %>%
  distinct(sub, session, age) %>%
  group_by(sub) %>%
  mutate(age_diff_raw = age - lag(age, n = 1),
         age_diff = ifelse(is.na(age_diff_raw), 0, age_diff_raw))

rockland_aparc2009_clean <- left_join(rockland_aparc2009_clean1, age_diffs) %>%
  group_by(sub) %>%
  mutate(max_age_diff = max(age_diff), 
         include_cc = max_age_diff > 30/365)

rockland_aparc2009_clean_cc <- rockland_aparc2009_clean %>%
  group_by(sub) %>%
  mutate(max_age_diff = max(age_diff)) %>%
  filter(max_age_diff > 30/365)
```

```{r}
theme_update(panel.background = element_rect(fill = 'white'), 
             axis.line = element_line(size=0),
             strip.background = element_rect(fill='white'),
             legend.key = element_rect(fill='white'))

plot_acc_design <- function(adf, adf_limited = NULL){
  if(!is.null(adf_limited)){
    sublist <- unique(adf_limited$sub)
    adf <- adf %>%
      mutate(Excluded = !sub %in% sublist)
    point_aesthetic <- aes(x = age, y = factor(as.numeric(sub)), color = Excluded)
  } else {
    point_aesthetic <- aes(x = age, y = factor(as.numeric(sub)))
  }
  subj_min_age <- adf %>% 
    group_by(sub) %>%
    summarize(age = round(min(age),0), n = n()) %>%
    ungroup() %>%
    arrange(age, n)
  
  subject_range <- 1:dim(subj_min_age)[1]
  
  accelerated_design_plot <- adf %>% 
    ungroup %>%
    mutate(sub = factor(sub, levels = subj_min_age$sub)) %>%
    ggplot(aes(x = age, y = factor(as.numeric(sub)))) +
    scale_x_continuous(breaks = c(seq(6, 22, 4))) +
    scale_y_discrete(labels = c(),
                     breaks = c())+
    geom_line(alpha = .5, size = .25) + 
    geom_point(point_aesthetic, size = .5, alpha = .5) + 
    theme() + 
    labs(x = 'Age (years)', y = 'Participant')
  
  if(!is.null(adf_limited)){
    accelerated_design_plot_final <- accelerated_design_plot +
      scale_color_manual(values = c('black', 'red'),
                         breaks = c(T), 
                         labels = c('Excluded from\n"complete case"\nanalysis'),
                         guide = guide_legend(override.aes = list(alpha = 1, size = 2), 
                                              title = '',
                                              label.position = 'right'))
  } else {
    accelerated_design_plot_final <- accelerated_design_plot
  }
  
  return(accelerated_design_plot_final)
}

both_plot <- plot_acc_design(distinct(rockland_aparc2009_clean, sub, session, age, .keep_all = T), 
                             distinct(rockland_aparc2009_clean_cc, sub, session, age, .keep_all = T))+
  theme(legend.position = c(.85,.25))
print(both_plot)

clean_plot <- plot_acc_design(distinct(rockland_aparc2009_clean, sub, session, age, .keep_all = T))
print(clean_plot)

clean_cc_plot <- plot_acc_design(distinct(rockland_aparc2009_clean_cc, sub, session, age, .keep_all = T))
print(clean_cc_plot)

ggsave(filename = '/home/jflournoy/Documents/Notes/Projects/DCN_Special_Issue/Missingness/manuscript/rockland_data_pattern.pdf', 
       plot = both_plot, 
       width = 6.5,
       height = 3,
       units = 'in')
```

```{r}
models_cc <- rockland_aparc2009_clean %>%
  group_by(StructName, h) %>%
  filter(include_cc) %>%
  do({
    adf <- data_frame(aMod = list(lmer(ThickAvg ~ 1 + age_c + age_c_2 + (1 | sub), data = .)))
    adf$ngrps = ngrps(adf$aMod[[1]])
    adf$nobs = nobs(adf$aMod[[1]])
    return(adf)
  }) %>%
  mutate(data_set = 'cc')
models_avail <- rockland_aparc2009_clean %>%
  group_by(StructName, h) %>%
  do({
    adf <- data_frame(aMod = list(lmer(ThickAvg ~ 1 + age_c + age_c_2 + (1 | sub), data = .)))
    adf$ngrps = ngrps(adf$aMod[[1]])
    adf$nobs = nobs(adf$aMod[[1]])
    return(adf)
  }) %>%
  mutate(data_set = 'avail')

models <- bind_rows(models_cc, models_avail)

model_fe <- models %>% 
  group_by(StructName, h, data_set, nobs, ngrps) %>% 
  do({
    coefs <- coef(summary(.$aMod[[1]]))
    coefs_df <- as_data_frame(coefs)
    coefs_df$param <- rownames(coefs)
    return(coefs_df)
  })

model_estimate_stats <- model_fe %>% ungroup() %>%
  select(-nobs, -ngrps) %>%
  gather(stat, value, Estimate, `Std. Error`, `t value`) %>%
  filter(stat %in% c('Estimate', 'Std. Error')) %>%
  spread(data_set, value) %>%
  mutate(perc_diff = (cc - avail)/avail*100,
         abs_perc_diff = abs(perc_diff),
         sign_flip = avail*cc < 0)

quick_t_p <- function(t, df){
  pt(abs(t), df = df, lower.tail = F)*2
}

power_to_detect <- model_fe %>% 
  ungroup() %>%
  select(-Estimate, -`Std. Error`) %>%
  mutate(p_lib = quick_t_p(t = `t value`, df = nobs - 3)*68,
         p_cons = quick_t_p(t = `t value`, df = ngrps - 3)*68,
         sig_lib = p_lib < .05,
         sig_cons = p_cons < .05) %>%
  select(-`t value`, -nobs, -ngrps, -p_lib, -p_cons) %>%
  gather(stat, value,  sig_lib, sig_cons) %>%
  spread(data_set, value) %>%
  mutate(agreement = 1 + avail + 2*cc)

agreement <- power_to_detect %>%
  select(-avail, -cc) %>%
  filter(param != '(Intercept)',
         stat == 'sig_cons') %>%
  mutate(agreement = c('Neither', 'Available data', 'Complete Cases', 'Both')[agreement]) %>%
  spread(param, agreement) %>%
  select(-stat) %>%
  unite(StructName, StructName, h, sep = '.') 


age_c_df <- as.data.frame(table(agreement[, c('age_c')]))
age_c_df$param <- 'age_c'
age_c_2_df <- as.data.frame(table(agreement[, c('age_c_2')]))
age_c_2_df$param <- 'age_c_2'

param_sig_freq_df <- bind_rows(age_c_df, age_c_2_df) %>%
  spread(param, Freq, fill = 0) %>%
  mutate(Var1 = factor(Var1, levels = c('Neither', 'Available data', 'Complete Cases', 'Both')))



write(knitr::kable(arrange(param_sig_freq_df, Var1), col.names = c('Sigificant in ...', 'Linear Age', 'Quadratic Age'), format = 'latex'),
      file = file.path('/home/jflournoy/Documents/Notes/Projects/DCN_Special_Issue/Missingness/manuscript/', 'rockland_summary_table.txt'))
write(knitr::kable(filter(agreement, grepl('\\.l$', StructName)), col.names = c('Structure (left hemisphere)', 'Linear Age', 'Quadratic Age'), format = 'latex'),
      file = file.path('/home/jflournoy/Documents/Notes/Projects/DCN_Special_Issue/Missingness/manuscript/', 'rockland_parcel_table.txt'))


```

```{r}
theme_update(panel.background = element_rect(fill = 'white'), 
             axis.line = element_line(size=0),
             strip.background = element_rect(fill='white'),
             legend.key = element_rect(fill='white'))

nada <- model_estimate_stats %>%
  group_by(param, stat) %>%
  filter(param != '(Intercept)') %>%
  do({
    if (.$stat[[1]] == 'Std. Error'){
      binwidth = 5
      xlims <- c(0, 60)
      } else {
      binwidth = 20
      xlims <- quantile(.$perc_diff, probs = c(.05, .95))
      }
    filename <- file.path('/home/jflournoy/Documents/Notes/Projects/DCN_Special_Issue/Missingness/manuscript/', paste0('rockland_', .$stat[[1]], '_', .$param[[1]], '.pdf'))
    param <- c('(Intercept)' = 'Intercept', 'age_c' = 'Age', 'age_c_2' = expression(Age^2))[.$param[[1]]][[1]]
    xmedian <- median(.$perc_diff)
    # abs_median <- median(.$abs_perc_diff)
    aplot <- ggplot(., aes(x=perc_diff))+
      geom_histogram(fill = '#666666', binwidth = binwidth)+
      coord_cartesian(x = xlims)+
      geom_vline(xintercept = 0, color = 'black')+
      geom_vline(xintercept = xmedian, color = 'red', linetype = 2, size = 1)+
      labs(title = bquote(paste(.(.$stat[[1]]),': ', .(param))),
           x = 'Percent Difference',
           y = 'Count')
    print(aplot)
    print(paste0(.$stat[[1]], ' ', .$param[[1]],': ', xmedian))
    # print(paste0('abs med ', .$stat[[1]], ' ', .$param[[1]],': ', abs_median))
    ggsave(filename = filename, aplot, width = (8.5-2)/2, height = (11-2)/3, units = 'in')
    return(data_frame(plot = list(aplot)))
  })

```

```{r}
# test_data <- rockland_aparc2009_clean %>% filter(StructName == 'cuneus', h == 'l') 
# 
# aModel_big <- lmer(ThickAvg ~ 1 + poly(age, 2) + (1 | sub) + (1 | h:StructName), data = rockland_aparc2009_clean)
# aModel_big_reAge <- lmer(ThickAvg ~ 1 + poly(age, 2) + (1 | sub) + (1 + poly(age, 1) | h:StructName), data = rockland_aparc2009_clean)
# aModel_big_reAge2 <- lmer(ThickAvg ~ 1 + poly(age, 2) + (1 | sub) + (1 + poly(age, 2) | h:StructName), data = rockland_aparc2009_clean)
# aModel_big_struct <- lmer(ThickAvg ~ 1 + poly(age, 2) + (1 | sub) + (1 | StructName), data = rockland_aparc2009_clean)
# aModel_big_reAge_struct <- lmer(ThickAvg ~ 1 + poly(age, 2) + (1 | sub) + (1 + poly(age, 1) | StructName), data = rockland_aparc2009_clean)
# aModel_big_reAge2_struct <- lmer(ThickAvg ~ 1 + poly(age, 2) + (1 | sub) + (1 + poly(age, 2) | StructName), data = rockland_aparc2009_clean)
# 
# library(lattice)
# dotplot(ranef(aModel_big_reAge2_struct, condVar = TRUE))
# ranef(aModel_big_reAge2_struct, condVar = TRUE)
# 
# library(merTools)
# preds <- predictInterval(aModel_big_reAge2_struct, newdata = rockland_aparc2009_clean, n.sims = 999, .parallel = T)
# 
# 
# summary(aModel_big_reAge2_struct)
# 
# comparison_rez <- anova(aModel_big, aModel_big_struct, aModel_big_reAge, aModel_big_reAge_struct, aModel_big_reAge2,aModel_big_reAge2_struct)
# comparison_rez
# comparison_rez_REML <- anova(aModel_big, aModel_big_struct, aModel_big_reAge, aModel_big_reAge_struct, aModel_big_reAge2,aModel_big_reAge2_struct, refit=F)
# comparison_rez_REML
# 
# library(optimx)
# aModel_big_FEstruct_REsub <- lmer(ThickAvg ~ 1 + poly(age, 2)*StructName + (1 | sub), data = rockland_aparc2009_clean,
#                             control=lmerControl(optimizer="optimx",
#                                                 optCtrl=list(method="bobyqa")))
# aModel_big_FEstruct_REint <- lmer(ThickAvg ~ 1 + poly(age, 2)*StructName + (1 | sub) + (1 | StructName), data = rockland_aparc2009_clean,
#                             control=lmerControl(optimizer="optimx",
#                                                 optCtrl=list(method="bobyqa")))
# aModel_big_FEstruct_RE1 <- lmer(ThickAvg ~ 1 + poly(age, 2)*StructName + (1 | sub) + (1 + poly(age, 1) | StructName), data = rockland_aparc2009_clean,
#                             control=lmerControl(optimizer="optimx",
#                                                 optCtrl=list(method="L-BFGS-B")))
# aModel_big_FEstruct_RE2 <- lmer(ThickAvg ~ 1 + poly(age, 2)*StructName + (1 | sub) + (1 + poly(age, 2) | StructName), data = rockland_aparc2009_clean,
#                             control=lmerControl(optimizer="optimx",
#                                                 optCtrl=list(method="bobyqa")))
# anova(aModel_big_FEstruct_REsub, aModel_big_FEstruct_REint, aModel_big_FEstruct_RE1, aModel_big_FEstruct_RE2, refit=F)
# 
# summary(aModel_big_FEstruct_REsub)
# 
# rockland_aparc2009_clean$predicted <- predict(aModel_big_reAge2_struct, newdata = rockland_aparc2009_clean, re.form = ~(1 + poly(age, 2) | StructName))
# 
# ggplot(filter(rockland_aparc2009_clean, h == 'l'), 
#        aes(x = age, y = predicted, color = interaction(h, StructName), group = interaction(h, StructName)))+
#   geom_line()
# 
# summary(aModel_big)
# modelcoef <- coef(aModel_big)
# modelcoef$`h:StructName`

```

